name: Test
on:
  push:
    branches:
      - "*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make .env file
        run: cp .env.development .env
      - name: Run unit tests and coverage
        run: |
          yarn
          yarn test
          yarn coverage
  static-analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Make .env file
      run: cp .env.development .env
    - name: Load .env file
      run: |
        set -a # automatically export all variables
        source .env
        set +a
    - name: Install dependencies
      run: yarn
    - name: Run Slither
      uses: crytic/slither-action@v0.1.1
      continue-on-error: false
      id: slither
      with:
        node-version: 16
        sarif: results.sarif
        target: contracts
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.slither.outputs.sarif }}
